version: "3.8"

networks:
  my_network:

services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: User
    volumes:
      - data:/var/lib/postgres/data
    networks:
      - my_network

  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    ports:
      # AMQP protocol port
      - "5672:5672"
      # HTTP management UI
      - "15672:15672"
    networks:
      - my_network

  auth:
    stdin_open: true
    build:
      context: ./auth
      dockerfile: Dockerfile
    container_name: prisma-postgres-api
    depends_on:
      - postgres
    ports:
      - 3000:3000
    networks:
      - my_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - postgres
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - my_network

  products:
    build:
      context: ./products
    environment:
      PORT: "3002"
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - 3002:3002
    networks:
      - my_network

volumes:
  data:
  pgadmin-data:
